### ISSUE TITLE
missingpy problem

### ISSUE THREAD

**Issue by ariercole** [vanderschaarlab/clairvoyance#2]
Not directly a clairvoyance problems but some missingpy 0.2.0 components try to import sklearn.neighbors.base which isn’t right anymore as that’s now been renamed sklearn.neighbors._base since sklearn 0.22.1 I believe. Have reported issue to missingpy but work around is to modify missingpy components directly.

**Comment by DrShushen** [comment]
Dependency-related issue - will be addressed in the overhaul of dependencies.
