### ISSUE TITLE
gain_imputation.py code tries to import deprecated tensorflow class

### ISSUE THREAD

**Issue by ariercole** [vanderschaarlab/clairvoyance#3]
The gain_imputation.py code tries to import deprecated tensorflow.saved_model.tag_constants.

Fortunately the tags don't seem to be required as far as I can see so

> tf.saved_model.loader.load(sess, [tag_constants.SERVING], self.save_file_directory) 

can be replaced by

> tf.saved_model.loader.load(sess, self.save_file_directory)

**Comment by DrShushen** [comment]
Dependency-related issue - will be addressed in the overhaul of dependencies.
