### ISSUE TITLE
CRN_Base.py LSTMCell / DropoutWrapped import deprecated

### ISSUE THREAD

**Issue by ariercole** [vanderschaarlab/clairvoyance#4]
In CRN_Base.py, 
> from tensorflow.contrib.rnn import LSTMCell, DropoutWrapper
does not work because it has been moved. 

Instead call (at least for now) 
> from tensorflow.compat.v1.nn.rnn_cell import LSTMCell

**Comment by DrShushen** [comment]
Dependency-related issue - will be addressed in the overhaul of dependencies.
