### ISSUE TITLE
model_rnn.py use of deprecated tf.contrib.rnn.RNNCell

### ISSUE THREAD

**Issue by ariercole** [vanderschaarlab/clairvoyance#6]
In treatments/RMSN/libs/model_rnn.py, 

tf.contrib.rnn.RNNCell has been moved to tf.compat.v1.nn.rnn_cell.RNNCell (couple of defs:)

**Comment by DrShushen** [comment]
Dependency-related issue - will be addressed in the overhaul of dependencies.
