### ISSUE TITLE
Extension of models to more complex structures

### ISSUE THREAD

**Issue by Mvdnheuv** [vanderschaarlab/clairvoyance#7]
Hi,
Just wanted to ask if there are any plans to include other models into the package that your lab has developed. Specifically Dynamic-Deephit and DCN-PD would be great to have.

**Comment by DrShushen** [comment]
Hi,
We're actively working on Clairvoyance right now. The main focus is to first improve the robustness of the codebase. As part of this, we are also working to make it easy to "drop in" any model as long as it follows a simple interface - that way you would be able to easily add any of the lab's (or even your own) models. Please watch this repo for updates, a number of major overhauls are coming in the next months.
