### ISSUE TITLE
Tutorial fail because using mimic dataset and not mimic_antibiotics

### ISSUE THREAD

**Issue by IceQueen1996** [vanderschaarlab/clairvoyance#8]
Would it be possible to share the scripts to get the mimic dataset needed for the tutorials about prediction and active sensing. It uses to "normal" mimic dataset, but only for the mimim_antibiotics dataset the data extraction script is given.

It's a wonderful package and very well written and documented ;) Congrats to that.

Best wishes, Elly

**Comment by DrShushen** [comment]
Hi Elly,
Thank you for your request.
I am currently working on trying to consolidate the data preprocessing scripts - and still haven't been able to find this.
@ioanabica would you be able to help with this (the preprocessing for `mimic` rather than `mimic_antibiotics`)?

**Comment by DrShushen** [comment]
@IceQueen1996 Alternatively, please contact me by email, see here (scroll to Research Engineer / Evgeny Saveliev) https://www.vanderschaar-lab.com/research-team/
