### ISSUE TITLE
Dead link in prediction tutorial

### ISSUE THREAD

**Issue by MartinBernstorff** [vanderschaarlab/clairvoyance#9]
Thanks so much for your work on this! 

I'm trying to run the tutorial [here](https://github.com/jsyoon0823/time-series-automl.git), but the link to https://github.com/jsyoon0823/time-series-automl.git is dead. Any updates on that? :-)

Thanks!

**Comment by j2moreno** [comment]
Any update? Still dead link

**Comment by DrShushen** [comment]
Downloading this repo manually is no longer needed. We have now removed the text about downloading this from the tutorials.
